# Bussines Problem
<b> The Financial Technology company (Fin-Tech Company)</b> launch there a mobile app. This app used for financial purposes like bank loans, savings, etc. in one place. It has two versions free and premium. The free version app contains basic features and customer wants to use the premium feature then they have to pay some amount to unlock it.
   <br> 
    The main goal of the company is to sell the premium version app with low advertisement cost but they don’t know how to do it. That’s a reason they are provided the premium feature in the free version app for 24 hours to collect the customer’s behavior. After that, the company hired the Machine Learning Engineer to find insight from the collected data (customer’s behavior).
 <br> 
The job of the ML engineer is to find or predict new customer who is interested to buy the product or not. If the customers will buy a product anyway so no need to give an offer to that customer and loss the business. Only give offers to those customers who are interested to use premium version app but they can’t afford its cost. So the company will give offers to those customers and earn more money.

# Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from dateutil import parser # for columns like 'first_open' & 'enrolled_date'

# Importing the dataset that was created while Feature Engineering

In [3]:
df= pd.read_csv('new_appdata10.csv')

In [4]:
df.head(10)

,user,dayofweek,hour,age,numscreens,minigame,used_premium_feature,enrolled,liked,location,...,SecurityModal,ResendToken,TransactionList,NetworkFailure,ListPicker,other,SavingsCount,CMCount,CCCount,LoansCount
0,235136,3,02:00:00,23,15,0,0,0,0,0,...,0,0,0,0,0,7,0,0,0,1
1,333588,6,01:00:00,24,13,0,0,0,0,1,...,0,0,0,0,0,5,0,0,0,1
2,254414,1,19:00:00,23,3,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,234192,4,16:00:00,28,40,0,0,1,0,1,...,0,0,0,0,0,6,0,3,0,1
4,51549,1,18:00:00,31,32,0,0,1,1,0,...,0,0,0,0,0,10,0,2,0,1
5,56480,2,09:00:00,20,14,0,0,1,0,0,...,0,0,0,0,0,6,0,2,0,1
6,144649,1,02:00:00,35,3,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
7,249366,1,03:00:00,26,41,0,1,0,0,0,...,0,0,1,0,0,8,0,2,0,1
8,372004,2,14:00:00,29,33,1,1,0,0,1,...,0,0,0,0,0,19,0,0,0,3
9,338013,4,18:00:00,26,19,0,0,1,0,1,...,0,0,0,0,0,11,0,0,0,1

### Converting the hour column from float if not scaling will not be done

In [5]:
# First set of Feature cleaning
df["hour"] = df.hour.str.slice(1, 3).astype('int64')

In [6]:
df["hour"].dtypes

dtype('int64')

# Data Pre-Processing

In [7]:
x = df.loc[:, df.columns != "enrolled"]

In [8]:
y = df['enrolled']

In [9]:
x.head()

,user,dayofweek,hour,age,numscreens,minigame,used_premium_feature,liked,location,Institutions,...,SecurityModal,ResendToken,TransactionList,NetworkFailure,ListPicker,other,SavingsCount,CMCount,CCCount,LoansCount
0,235136,3,2,23,15,0,0,0,0,0,...,0,0,0,0,0,7,0,0,0,1
1,333588,6,1,24,13,0,0,0,1,1,...,0,0,0,0,0,5,0,0,0,1
2,254414,1,19,23,3,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,234192,4,16,28,40,0,0,0,1,0,...,0,0,0,0,0,6,0,3,0,1
4,51549,1,18,31,32,0,0,1,0,1,...,0,0,0,0,0,10,0,2,0,1

In [10]:
y.head()

0    0
1    0
2    0
3    1
4    1
Name: enrolled, dtype: int64

# Split the Dataset

In [11]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
# Removing the User Id column as it is not a real feature.
# but at the end we will use this data associating the prediction from user it came from

train_identifier = x_train['user']
x_train = x_train.drop(columns=['user'])

test_identifier = x_test['user']
x_test = x_test.drop(columns=['user'])

In [13]:
# the user column is removed from x_train and x_test
x_train.head()

,dayofweek,hour,age,numscreens,minigame,used_premium_feature,liked,location,Institutions,VerifyPhone,...,SecurityModal,ResendToken,TransactionList,NetworkFailure,ListPicker,other,SavingsCount,CMCount,CCCount,LoansCount
20330,2,20,32,5,0,1,1,0,0,0,...,0,0,0,0,0,2,0,0,0,2
17532,1,21,22,42,1,0,0,1,1,1,...,0,0,0,0,0,13,0,1,0,1
45819,0,4,26,85,1,0,0,0,1,0,...,0,0,0,0,0,10,0,2,1,2
34807,4,13,25,24,1,0,0,1,0,0,...,0,0,0,0,0,10,0,0,0,1
31888,3,16,50,11,0,0,0,1,0,1,...,0,0,0,0,0,3,0,2,0,0

# Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [15]:
# train the x_train and create a new variable for scaled x_train
#Standard scaler returns a numpy array so we need to convert to DataFrame
#In array form 'index' and 'column names' are lost we need it so convert to Df

x_train_scaled= pd.DataFrame(sc.fit_transform(x_train))
x_test_scaled = pd.DataFrame(sc.transform(x_test))

In [16]:
# put x_train_scaled have the columns of original x_train set
x_train_scaled.columns = x_train.columns.values

# put x_test_scaled have the columns of original x_test set
x_test_scaled.columns = x_test.columns.values

# take the indexes also
x_train_scaled.index = x_train.index.values
x_test_scaled.index = x_test.index.values

In [17]:
# Compare the original training set with new scaled training set
x_train= x_train_scaled
x_test= x_test_scaled

##  Applying machine learning algorithms

<b> Note:If working for a mobile app model always take into consideration that the screens can be correlated.
    We have tried to avoid the correlation by creating funnels but tehre may be some screens that do not belong to the same set but still be correlated.
    So add a penalty of 'L1'

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = clf.predict(x_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(x_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

### LOGISTIC REGRESSION

In [21]:
# Fitting Model to the Training Set
# Importing the Classifier
# Penalty to avoid correlations if some screens belong to same set.

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(penalty='l2', random_state=0)
classifier.fit(x_train, y_train)

print_score(classifier, x_train, y_train, x_test, y_test, train=True)
print_score(classifier, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 76.75%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.769770      0.765335   0.76755      0.767552      0.767561
recall         0.766013      0.769099   0.76755      0.767556      0.767550
f1-score       0.767887      0.767212   0.76755      0.767550      0.767551
support    20078.000000  19922.000000   0.76755  40000.000000  40000.000000
_______________________________________________
Confusion Matrix:
 [[15380  4698]
 [ 4600 15322]]

Test Result:
================================================
Accuracy Score: 76.80%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy     macro avg  weighted avg
precision     0.774213     0.761742     0.768      0.767978      0.768067
recall        0.765970     0.770089     0.768      0.768030      0.768000
f1-score      0.770069     0.765893     0.768      0.767981      0.768011
support    5072.000000  4928.000000     0.768  10000.000000  10000.000000
_______________________________________________
Confusion Matrix:
 [[3885 1187]
 [1133 3795]]

## DECISION TREE

In [22]:
# DECISSION TREE

# Fitting Model to the Training Set
# Importing the Classifier

from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(x_train, y_train)

print_score(tree_clf, x_train, y_train, x_test, y_test, train=True)
print_score(tree_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 99.98%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.999651      1.000000  0.999825      0.999826      0.999825
recall         1.000000      0.999649  0.999825      0.999824      0.999825
f1-score       0.999826      0.999824  0.999825      0.999825      0.999825
support    20078.000000  19922.000000  0.999825  40000.000000  40000.000000
_______________________________________________
Confusion Matrix:
 [[20078     0]
 [    7 19915]]

Test Result:
================================================
Accuracy Score: 69.51%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy     macro avg  weighted avg
precision     0.702340     0.687862    0.6951      0.695101      0.695206
recall        0.692232     0.698052    0.6951      0.695142      0.695100
f1-score      0.697250     0.692920    0.6951      0.695085      0.695116
support    5072.000000  4928.000000    0.6951  10000.000000  10000.000000
_______________________________________________
Confusion Matrix:
 [[3511 1561]
 [1488 3440]]

## RANDOM FOREST

In [24]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=5)
rf_clf.fit(x_train, y_train)

print_score(rf_clf, x_train, y_train, x_test, y_test, train=True)
print_score(rf_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 96.84%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.967641      0.969269   0.96845      0.968455      0.968452
recall         0.969569      0.967323   0.96845      0.968446      0.968450
f1-score       0.968604      0.968295   0.96845      0.968449      0.968450
support    20078.000000  19922.000000   0.96845  40000.000000  40000.000000
_______________________________________________
Confusion Matrix:
 [[19467   611]
 [  651 19271]]

Test Result:
================================================
Accuracy Score: 74.32%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy     macro avg  weighted avg
precision     0.746457     0.739837    0.7432      0.743147      0.743195
recall        0.747634     0.738636    0.7432      0.743135      0.743200
f1-score      0.747045     0.739236    0.7432      0.743141      0.743197
support    5072.000000  4928.000000    0.7432  10000.000000  10000.000000
_______________________________________________
Confusion Matrix:
 [[3792 1280]
 [1288 3640]]

## SVM
<b>  Linear Kernel SVM

In [25]:
from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(x_train, y_train)

print_score(model, x_train, y_train, x_test, y_test, train=True)
print_score(model, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 76.76%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.773389      0.762020  0.767625      0.767704      0.767726
recall         0.759637      0.775675  0.767625      0.767656      0.767625
f1-score       0.766451      0.768787  0.767625      0.767619      0.767615
support    20078.000000  19922.000000  0.767625  40000.000000  40000.000000
_______________________________________________
Confusion Matrix:
 [[15252  4826]
 [ 4469 15453]]

Test Result:
================================================
Accuracy Score: 76.76%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy     macro avg  weighted avg
precision     0.776904     0.758436    0.7676      0.767670      0.767803
recall        0.760055     0.775365    0.7676      0.767710      0.767600
f1-score      0.768387     0.766807    0.7676      0.767597      0.767609
support    5072.000000  4928.000000    0.7676  10000.000000  10000.000000
_______________________________________________
Confusion Matrix:
 [[3855 1217]
 [1107 3821]]

C:\Users\ebineet\Anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

## Polynomial Kernel SVM
<br>
<strong>This code trains a SVM classifier using 2rd degree ploynomial kernel.

In [26]:
from sklearn.svm import SVC

# The hyperparameter coef0 controls how much the model is influenced by high degree ploynomials 
model = SVC(kernel='poly', degree=2, gamma='auto', coef0=1, C=1)
model.fit(x_train, y_train)

print_score(model, x_train, y_train, x_test, y_test, train=True)
print_score(model, x_train, y_train, x_test, y_test, train=False)

Train Result:
================================================
Accuracy Score: 78.27%
_______________________________________________
CLASSIFICATION REPORT:
                      0             1  accuracy     macro avg  weighted avg
precision      0.780311      0.785061   0.78265      0.782686      0.782677
recall         0.789172      0.776077   0.78265      0.782624      0.782650
f1-score       0.784717      0.780543   0.78265      0.782630      0.782638
support    20078.000000  19922.000000   0.78265  40000.000000  40000.000000
_______________________________________________
Confusion Matrix:
 [[15845  4233]
 [ 4461 15461]]

Test Result:
================================================
Accuracy Score: 77.32%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy     macro avg  weighted avg
precision     0.772763     0.773663    0.7732      0.773213      0.773206
recall        0.783123     0.762987    0.7732      0.773055      0.773200
f1-score      0.777908     0.768288    0.7732      0.773098      0.773167
support    5072.000000  4928.000000    0.7732  10000.000000  10000.000000
_______________________________________________
Confusion Matrix:
 [[3972 1100]
 [1168 3760]]

## Hyper Parameter Tuning

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid = {'C': [0.01, 0.1, 0.5, 1, 10, 100], 
              'gamma': [1, 0.75, 0.5, 0.25, 0.1, 0.01, 0.001], 
              'kernel': ['rbf', 'linear']} 

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=1, cv=5, iid=True,n_jobs=-1)
grid.fit(x_train, y_train)

best_params = grid.best_params_
print(f"Best params: {best_params}")

svm_clf = SVC(**best_params)
svm_clf.fit(x_train, y_train)
print_score(svm_clf, x_train, y_train, x_test, y_test, train=True)